
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node
    args: ['install']
    entrypoint: npm
    timeout: 300s

  - name: node
    args: ['run', 'build']
    entrypoint: npm
    timeout: 300s

  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-c'
      - |
        git config --global user.email "98767786228@cloudbuild.gserviceaccount.com"
        git config --global user.name "Cloud Build Service Account"
        gcloud source repos clone wheelersadvice/cicd/web --project=cloudguruchallenge-2108
        cd wheelersadvice/cicd/web
        git checkout candidate
        rm -r dist/
        cp -r /workspace/dist/ dist/
        git add dist/
        git commit -m "web deployment for $COMMIT_SHA"
        git push -u origin candidate
    entrypoint: /bin/sh
    timeout: 300s
